<?php


/**
 * This class adds structure of 'contacte' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jul  7 09:52:35 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogContactePlugin.lib.model.map
 */
class ContacteMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogContactePlugin.lib.model.map.ContacteMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ContactePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ContactePeer::TABLE_NAME);
		$tMap->setPhpName('Contacte');
		$tMap->setClassname('Contacte');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('TIPUS_PERSONA', 'TipusPersona', 'VARCHAR', true, 1);

		$tMap->addColumn('NOM', 'Nom', 'VARCHAR', true, 255);

		$tMap->addColumn('COGNOMS', 'Cognoms', 'VARCHAR', true, 255);

		$tMap->addColumn('DNI', 'Dni', 'VARCHAR', false, 12);

		$tMap->addColumn('DIRECCIO', 'Direccio', 'VARCHAR', false, 255);

		$tMap->addColumn('CODI_POSTAL', 'CodiPostal', 'VARCHAR', false, 10);

		$tMap->addColumn('CIUTAT', 'Ciutat', 'VARCHAR', true, 100);

		$tMap->addColumn('PROVINCIA', 'Provincia', 'VARCHAR', false, 100);

		$tMap->addColumn('PAIS_RESIDENCIA', 'PaisResidencia', 'VARCHAR', false, 100);

		$tMap->addColumn('TELEFON', 'Telefon', 'VARCHAR', false, 11);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 255);

		$tMap->addColumn('DATA_NAIXEMENT', 'DataNaixement', 'DATE', false, null);

		$tMap->addColumn('NACIONALITAT', 'Nacionalitat', 'VARCHAR', true, 100);

		$tMap->addColumn('IDIOMA_CONTACTE', 'IdiomaContacte', 'VARCHAR', true, 2);

		$tMap->addColumn('SEXE', 'Sexe', 'VARCHAR', false, 1);

		$tMap->addColumn('ACCEPTA_MAILING', 'AcceptaMailing', 'BOOLEAN', false, null);

		$tMap->addColumn('TEXT', 'Text', 'LONGVARCHAR', true, null);

	} // doBuild()

} // ContacteMapBuilder
