<?php


/**
 * This class adds structure of 'donacio' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jul  7 09:52:35 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.iogContactePlugin.lib.model.map
 */
class DonacioMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.iogContactePlugin.lib.model.map.DonacioMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(DonacioPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(DonacioPeer::TABLE_NAME);
		$tMap->setPhpName('Donacio');
		$tMap->setClassname('Donacio');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NOM', 'Nom', 'VARCHAR', true, 255);

		$tMap->addColumn('COGNOMS', 'Cognoms', 'VARCHAR', true, 255);

		$tMap->addColumn('ENTITAT', 'Entitat', 'VARCHAR', false, 255);

		$tMap->addColumn('DIRECCIO', 'Direccio', 'VARCHAR', false, 255);

		$tMap->addColumn('CODI_POSTAL', 'CodiPostal', 'VARCHAR', false, 10);

		$tMap->addColumn('CIUTAT', 'Ciutat', 'VARCHAR', true, 100);

		$tMap->addColumn('TELEFON', 'Telefon', 'VARCHAR', false, 15);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 255);

		$tMap->addColumn('PROFESSIO', 'Professio', 'VARCHAR', false, 255);

		$tMap->addColumn('DNI', 'Dni', 'VARCHAR', false, 12);

		$tMap->addColumn('DATA_NAIXEMENT', 'DataNaixement', 'DATE', false, null);

		$tMap->addColumn('DONACIO', 'Donacio', 'DECIMAL', false, 8);

		$tMap->addColumn('PERIODICITAT', 'Periodicitat', 'VARCHAR', true, 255);

		$tMap->addColumn('FORMA_PAGAMENT', 'FormaPagament', 'VARCHAR', true, 255);

		$tMap->addColumn('CC', 'Cc', 'INTEGER', false, 10);

		$tMap->addColumn('OFICINA', 'Oficina', 'INTEGER', false, 4);

		$tMap->addColumn('DC', 'Dc', 'INTEGER', false, 2);

		$tMap->addColumn('ENTITAT_COMPTE', 'EntitatCompte', 'INTEGER', false, 4);

		$tMap->addColumn('TITULAR_COMPTE', 'TitularCompte', 'VARCHAR', false, 255);

		$tMap->addColumn('NEWSLETTER', 'Newsletter', 'BOOLEAN', false, null);

		$tMap->addColumn('NB_PEDIDO', 'NbPedido', 'INTEGER', false, 11);

		$tMap->addColumn('RESPONSE', 'Response', 'VARCHAR', false, 10);

	} // doBuild()

} // DonacioMapBuilder
