<?php

/**
 * Base class that represents a row from the 'contacte' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jul  7 09:52:35 2011
 *
 * @package    plugins.iogContactePlugin.lib.model.om
 */
abstract class BaseContacte extends BaseObject  implements Persistent {


  const PEER = 'ContactePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ContactePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the tipus_persona field.
	 * Note: this column has a database default value of: 'p'
	 * @var        string
	 */
	protected $tipus_persona;

	/**
	 * The value for the nom field.
	 * @var        string
	 */
	protected $nom;

	/**
	 * The value for the cognoms field.
	 * @var        string
	 */
	protected $cognoms;

	/**
	 * The value for the dni field.
	 * @var        string
	 */
	protected $dni;

	/**
	 * The value for the direccio field.
	 * @var        string
	 */
	protected $direccio;

	/**
	 * The value for the codi_postal field.
	 * @var        string
	 */
	protected $codi_postal;

	/**
	 * The value for the ciutat field.
	 * @var        string
	 */
	protected $ciutat;

	/**
	 * The value for the provincia field.
	 * @var        string
	 */
	protected $provincia;

	/**
	 * The value for the pais_residencia field.
	 * @var        string
	 */
	protected $pais_residencia;

	/**
	 * The value for the telefon field.
	 * @var        string
	 */
	protected $telefon;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the data_naixement field.
	 * @var        string
	 */
	protected $data_naixement;

	/**
	 * The value for the nacionalitat field.
	 * @var        string
	 */
	protected $nacionalitat;

	/**
	 * The value for the idioma_contacte field.
	 * Note: this column has a database default value of: 'ca'
	 * @var        string
	 */
	protected $idioma_contacte;

	/**
	 * The value for the sexe field.
	 * @var        string
	 */
	protected $sexe;

	/**
	 * The value for the accepta_mailing field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $accepta_mailing;

	/**
	 * The value for the text field.
	 * @var        string
	 */
	protected $text;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseContacte object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->tipus_persona = 'p';
		$this->idioma_contacte = 'ca';
		$this->accepta_mailing = false;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [tipus_persona] column value.
	 * 
	 * @return     string
	 */
	public function getTipusPersona()
	{
		return $this->tipus_persona;
	}

	/**
	 * Get the [nom] column value.
	 * 
	 * @return     string
	 */
	public function getNom()
	{
		return $this->nom;
	}

	/**
	 * Get the [cognoms] column value.
	 * 
	 * @return     string
	 */
	public function getCognoms()
	{
		return $this->cognoms;
	}

	/**
	 * Get the [dni] column value.
	 * 
	 * @return     string
	 */
	public function getDni()
	{
		return $this->dni;
	}

	/**
	 * Get the [direccio] column value.
	 * 
	 * @return     string
	 */
	public function getDireccio()
	{
		return $this->direccio;
	}

	/**
	 * Get the [codi_postal] column value.
	 * 
	 * @return     string
	 */
	public function getCodiPostal()
	{
		return $this->codi_postal;
	}

	/**
	 * Get the [ciutat] column value.
	 * 
	 * @return     string
	 */
	public function getCiutat()
	{
		return $this->ciutat;
	}

	/**
	 * Get the [provincia] column value.
	 * 
	 * @return     string
	 */
	public function getProvincia()
	{
		return $this->provincia;
	}

	/**
	 * Get the [pais_residencia] column value.
	 * 
	 * @return     string
	 */
	public function getPaisResidencia()
	{
		return $this->pais_residencia;
	}

	/**
	 * Get the [telefon] column value.
	 * 
	 * @return     string
	 */
	public function getTelefon()
	{
		return $this->telefon;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [optionally formatted] temporal [data_naixement] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDataNaixement($format = 'Y-m-d')
	{
		if ($this->data_naixement === null) {
			return null;
		}


		if ($this->data_naixement === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->data_naixement);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->data_naixement, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [nacionalitat] column value.
	 * 
	 * @return     string
	 */
	public function getNacionalitat()
	{
		return $this->nacionalitat;
	}

	/**
	 * Get the [idioma_contacte] column value.
	 * 
	 * @return     string
	 */
	public function getIdiomaContacte()
	{
		return $this->idioma_contacte;
	}

	/**
	 * Get the [sexe] column value.
	 * 
	 * @return     string
	 */
	public function getSexe()
	{
		return $this->sexe;
	}

	/**
	 * Get the [accepta_mailing] column value.
	 * 
	 * @return     boolean
	 */
	public function getAcceptaMailing()
	{
		return $this->accepta_mailing;
	}

	/**
	 * Get the [text] column value.
	 * 
	 * @return     string
	 */
	public function getText()
	{
		return $this->text;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ContactePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [tipus_persona] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setTipusPersona($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipus_persona !== $v || $v === 'p') {
			$this->tipus_persona = $v;
			$this->modifiedColumns[] = ContactePeer::TIPUS_PERSONA;
		}

		return $this;
	} // setTipusPersona()

	/**
	 * Set the value of [nom] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setNom($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nom !== $v) {
			$this->nom = $v;
			$this->modifiedColumns[] = ContactePeer::NOM;
		}

		return $this;
	} // setNom()

	/**
	 * Set the value of [cognoms] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setCognoms($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cognoms !== $v) {
			$this->cognoms = $v;
			$this->modifiedColumns[] = ContactePeer::COGNOMS;
		}

		return $this;
	} // setCognoms()

	/**
	 * Set the value of [dni] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setDni($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dni !== $v) {
			$this->dni = $v;
			$this->modifiedColumns[] = ContactePeer::DNI;
		}

		return $this;
	} // setDni()

	/**
	 * Set the value of [direccio] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setDireccio($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->direccio !== $v) {
			$this->direccio = $v;
			$this->modifiedColumns[] = ContactePeer::DIRECCIO;
		}

		return $this;
	} // setDireccio()

	/**
	 * Set the value of [codi_postal] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setCodiPostal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->codi_postal !== $v) {
			$this->codi_postal = $v;
			$this->modifiedColumns[] = ContactePeer::CODI_POSTAL;
		}

		return $this;
	} // setCodiPostal()

	/**
	 * Set the value of [ciutat] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setCiutat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ciutat !== $v) {
			$this->ciutat = $v;
			$this->modifiedColumns[] = ContactePeer::CIUTAT;
		}

		return $this;
	} // setCiutat()

	/**
	 * Set the value of [provincia] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setProvincia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->provincia !== $v) {
			$this->provincia = $v;
			$this->modifiedColumns[] = ContactePeer::PROVINCIA;
		}

		return $this;
	} // setProvincia()

	/**
	 * Set the value of [pais_residencia] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setPaisResidencia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pais_residencia !== $v) {
			$this->pais_residencia = $v;
			$this->modifiedColumns[] = ContactePeer::PAIS_RESIDENCIA;
		}

		return $this;
	} // setPaisResidencia()

	/**
	 * Set the value of [telefon] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setTelefon($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefon !== $v) {
			$this->telefon = $v;
			$this->modifiedColumns[] = ContactePeer::TELEFON;
		}

		return $this;
	} // setTelefon()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = ContactePeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Sets the value of [data_naixement] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setDataNaixement($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->data_naixement !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->data_naixement !== null && $tmpDt = new DateTime($this->data_naixement)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->data_naixement = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = ContactePeer::DATA_NAIXEMENT;
			}
		} // if either are not null

		return $this;
	} // setDataNaixement()

	/**
	 * Set the value of [nacionalitat] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setNacionalitat($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nacionalitat !== $v) {
			$this->nacionalitat = $v;
			$this->modifiedColumns[] = ContactePeer::NACIONALITAT;
		}

		return $this;
	} // setNacionalitat()

	/**
	 * Set the value of [idioma_contacte] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setIdiomaContacte($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->idioma_contacte !== $v || $v === 'ca') {
			$this->idioma_contacte = $v;
			$this->modifiedColumns[] = ContactePeer::IDIOMA_CONTACTE;
		}

		return $this;
	} // setIdiomaContacte()

	/**
	 * Set the value of [sexe] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setSexe($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sexe !== $v) {
			$this->sexe = $v;
			$this->modifiedColumns[] = ContactePeer::SEXE;
		}

		return $this;
	} // setSexe()

	/**
	 * Set the value of [accepta_mailing] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setAcceptaMailing($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->accepta_mailing !== $v || $v === false) {
			$this->accepta_mailing = $v;
			$this->modifiedColumns[] = ContactePeer::ACCEPTA_MAILING;
		}

		return $this;
	} // setAcceptaMailing()

	/**
	 * Set the value of [text] column.
	 * 
	 * @param      string $v new value
	 * @return     Contacte The current object (for fluent API support)
	 */
	public function setText($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->text !== $v) {
			$this->text = $v;
			$this->modifiedColumns[] = ContactePeer::TEXT;
		}

		return $this;
	} // setText()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(ContactePeer::TIPUS_PERSONA,ContactePeer::IDIOMA_CONTACTE,ContactePeer::ACCEPTA_MAILING))) {
				return false;
			}

			if ($this->tipus_persona !== 'p') {
				return false;
			}

			if ($this->idioma_contacte !== 'ca') {
				return false;
			}

			if ($this->accepta_mailing !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->tipus_persona = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->nom = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->cognoms = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->dni = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->direccio = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->codi_postal = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->ciutat = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->provincia = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->pais_residencia = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->telefon = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->email = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->data_naixement = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->nacionalitat = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->idioma_contacte = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->sexe = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->accepta_mailing = ($row[$startcol + 16] !== null) ? (boolean) $row[$startcol + 16] : null;
			$this->text = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 18; // 18 = ContactePeer::NUM_COLUMNS - ContactePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Contacte object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ContactePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseContacte:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ContactePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseContacte:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseContacte:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseContacte:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ContactePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ContactePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ContactePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ContactePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ContactePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ContactePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTipusPersona();
				break;
			case 2:
				return $this->getNom();
				break;
			case 3:
				return $this->getCognoms();
				break;
			case 4:
				return $this->getDni();
				break;
			case 5:
				return $this->getDireccio();
				break;
			case 6:
				return $this->getCodiPostal();
				break;
			case 7:
				return $this->getCiutat();
				break;
			case 8:
				return $this->getProvincia();
				break;
			case 9:
				return $this->getPaisResidencia();
				break;
			case 10:
				return $this->getTelefon();
				break;
			case 11:
				return $this->getEmail();
				break;
			case 12:
				return $this->getDataNaixement();
				break;
			case 13:
				return $this->getNacionalitat();
				break;
			case 14:
				return $this->getIdiomaContacte();
				break;
			case 15:
				return $this->getSexe();
				break;
			case 16:
				return $this->getAcceptaMailing();
				break;
			case 17:
				return $this->getText();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ContactePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTipusPersona(),
			$keys[2] => $this->getNom(),
			$keys[3] => $this->getCognoms(),
			$keys[4] => $this->getDni(),
			$keys[5] => $this->getDireccio(),
			$keys[6] => $this->getCodiPostal(),
			$keys[7] => $this->getCiutat(),
			$keys[8] => $this->getProvincia(),
			$keys[9] => $this->getPaisResidencia(),
			$keys[10] => $this->getTelefon(),
			$keys[11] => $this->getEmail(),
			$keys[12] => $this->getDataNaixement(),
			$keys[13] => $this->getNacionalitat(),
			$keys[14] => $this->getIdiomaContacte(),
			$keys[15] => $this->getSexe(),
			$keys[16] => $this->getAcceptaMailing(),
			$keys[17] => $this->getText(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ContactePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTipusPersona($value);
				break;
			case 2:
				$this->setNom($value);
				break;
			case 3:
				$this->setCognoms($value);
				break;
			case 4:
				$this->setDni($value);
				break;
			case 5:
				$this->setDireccio($value);
				break;
			case 6:
				$this->setCodiPostal($value);
				break;
			case 7:
				$this->setCiutat($value);
				break;
			case 8:
				$this->setProvincia($value);
				break;
			case 9:
				$this->setPaisResidencia($value);
				break;
			case 10:
				$this->setTelefon($value);
				break;
			case 11:
				$this->setEmail($value);
				break;
			case 12:
				$this->setDataNaixement($value);
				break;
			case 13:
				$this->setNacionalitat($value);
				break;
			case 14:
				$this->setIdiomaContacte($value);
				break;
			case 15:
				$this->setSexe($value);
				break;
			case 16:
				$this->setAcceptaMailing($value);
				break;
			case 17:
				$this->setText($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ContactePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTipusPersona($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNom($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCognoms($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDni($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDireccio($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCodiPostal($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCiutat($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setProvincia($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPaisResidencia($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTelefon($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setEmail($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDataNaixement($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setNacionalitat($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setIdiomaContacte($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setSexe($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setAcceptaMailing($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setText($arr[$keys[17]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ContactePeer::DATABASE_NAME);

		if ($this->isColumnModified(ContactePeer::ID)) $criteria->add(ContactePeer::ID, $this->id);
		if ($this->isColumnModified(ContactePeer::TIPUS_PERSONA)) $criteria->add(ContactePeer::TIPUS_PERSONA, $this->tipus_persona);
		if ($this->isColumnModified(ContactePeer::NOM)) $criteria->add(ContactePeer::NOM, $this->nom);
		if ($this->isColumnModified(ContactePeer::COGNOMS)) $criteria->add(ContactePeer::COGNOMS, $this->cognoms);
		if ($this->isColumnModified(ContactePeer::DNI)) $criteria->add(ContactePeer::DNI, $this->dni);
		if ($this->isColumnModified(ContactePeer::DIRECCIO)) $criteria->add(ContactePeer::DIRECCIO, $this->direccio);
		if ($this->isColumnModified(ContactePeer::CODI_POSTAL)) $criteria->add(ContactePeer::CODI_POSTAL, $this->codi_postal);
		if ($this->isColumnModified(ContactePeer::CIUTAT)) $criteria->add(ContactePeer::CIUTAT, $this->ciutat);
		if ($this->isColumnModified(ContactePeer::PROVINCIA)) $criteria->add(ContactePeer::PROVINCIA, $this->provincia);
		if ($this->isColumnModified(ContactePeer::PAIS_RESIDENCIA)) $criteria->add(ContactePeer::PAIS_RESIDENCIA, $this->pais_residencia);
		if ($this->isColumnModified(ContactePeer::TELEFON)) $criteria->add(ContactePeer::TELEFON, $this->telefon);
		if ($this->isColumnModified(ContactePeer::EMAIL)) $criteria->add(ContactePeer::EMAIL, $this->email);
		if ($this->isColumnModified(ContactePeer::DATA_NAIXEMENT)) $criteria->add(ContactePeer::DATA_NAIXEMENT, $this->data_naixement);
		if ($this->isColumnModified(ContactePeer::NACIONALITAT)) $criteria->add(ContactePeer::NACIONALITAT, $this->nacionalitat);
		if ($this->isColumnModified(ContactePeer::IDIOMA_CONTACTE)) $criteria->add(ContactePeer::IDIOMA_CONTACTE, $this->idioma_contacte);
		if ($this->isColumnModified(ContactePeer::SEXE)) $criteria->add(ContactePeer::SEXE, $this->sexe);
		if ($this->isColumnModified(ContactePeer::ACCEPTA_MAILING)) $criteria->add(ContactePeer::ACCEPTA_MAILING, $this->accepta_mailing);
		if ($this->isColumnModified(ContactePeer::TEXT)) $criteria->add(ContactePeer::TEXT, $this->text);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ContactePeer::DATABASE_NAME);

		$criteria->add(ContactePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Contacte (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTipusPersona($this->tipus_persona);

		$copyObj->setNom($this->nom);

		$copyObj->setCognoms($this->cognoms);

		$copyObj->setDni($this->dni);

		$copyObj->setDireccio($this->direccio);

		$copyObj->setCodiPostal($this->codi_postal);

		$copyObj->setCiutat($this->ciutat);

		$copyObj->setProvincia($this->provincia);

		$copyObj->setPaisResidencia($this->pais_residencia);

		$copyObj->setTelefon($this->telefon);

		$copyObj->setEmail($this->email);

		$copyObj->setDataNaixement($this->data_naixement);

		$copyObj->setNacionalitat($this->nacionalitat);

		$copyObj->setIdiomaContacte($this->idioma_contacte);

		$copyObj->setSexe($this->sexe);

		$copyObj->setAcceptaMailing($this->accepta_mailing);

		$copyObj->setText($this->text);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Contacte Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ContactePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ContactePeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseContacte:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseContacte::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseContacte
