<?php

/**
 * Base static class for performing query and update operations on the 'donacio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jul  7 09:52:35 2011
 *
 * @package    plugins.iogContactePlugin.lib.model.om
 */
abstract class BaseDonacioPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'donacio';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.iogContactePlugin.lib.model.Donacio';

	/** The total number of columns. */
	const NUM_COLUMNS = 23;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'donacio.ID';

	/** the column name for the NOM field */
	const NOM = 'donacio.NOM';

	/** the column name for the COGNOMS field */
	const COGNOMS = 'donacio.COGNOMS';

	/** the column name for the ENTITAT field */
	const ENTITAT = 'donacio.ENTITAT';

	/** the column name for the DIRECCIO field */
	const DIRECCIO = 'donacio.DIRECCIO';

	/** the column name for the CODI_POSTAL field */
	const CODI_POSTAL = 'donacio.CODI_POSTAL';

	/** the column name for the CIUTAT field */
	const CIUTAT = 'donacio.CIUTAT';

	/** the column name for the TELEFON field */
	const TELEFON = 'donacio.TELEFON';

	/** the column name for the EMAIL field */
	const EMAIL = 'donacio.EMAIL';

	/** the column name for the PROFESSIO field */
	const PROFESSIO = 'donacio.PROFESSIO';

	/** the column name for the DNI field */
	const DNI = 'donacio.DNI';

	/** the column name for the DATA_NAIXEMENT field */
	const DATA_NAIXEMENT = 'donacio.DATA_NAIXEMENT';

	/** the column name for the DONACIO field */
	const DONACIO = 'donacio.DONACIO';

	/** the column name for the PERIODICITAT field */
	const PERIODICITAT = 'donacio.PERIODICITAT';

	/** the column name for the FORMA_PAGAMENT field */
	const FORMA_PAGAMENT = 'donacio.FORMA_PAGAMENT';

	/** the column name for the CC field */
	const CC = 'donacio.CC';

	/** the column name for the OFICINA field */
	const OFICINA = 'donacio.OFICINA';

	/** the column name for the DC field */
	const DC = 'donacio.DC';

	/** the column name for the ENTITAT_COMPTE field */
	const ENTITAT_COMPTE = 'donacio.ENTITAT_COMPTE';

	/** the column name for the TITULAR_COMPTE field */
	const TITULAR_COMPTE = 'donacio.TITULAR_COMPTE';

	/** the column name for the NEWSLETTER field */
	const NEWSLETTER = 'donacio.NEWSLETTER';

	/** the column name for the NB_PEDIDO field */
	const NB_PEDIDO = 'donacio.NB_PEDIDO';

	/** the column name for the RESPONSE field */
	const RESPONSE = 'donacio.RESPONSE';

	/**
	 * An identiy map to hold any loaded instances of Donacio objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Donacio[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Nom', 'Cognoms', 'Entitat', 'Direccio', 'CodiPostal', 'Ciutat', 'Telefon', 'Email', 'Professio', 'Dni', 'DataNaixement', 'Donacio', 'Periodicitat', 'FormaPagament', 'Cc', 'Oficina', 'Dc', 'EntitatCompte', 'TitularCompte', 'Newsletter', 'NbPedido', 'Response', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'nom', 'cognoms', 'entitat', 'direccio', 'codiPostal', 'ciutat', 'telefon', 'email', 'professio', 'dni', 'dataNaixement', 'donacio', 'periodicitat', 'formaPagament', 'cc', 'oficina', 'dc', 'entitatCompte', 'titularCompte', 'newsletter', 'nbPedido', 'response', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NOM, self::COGNOMS, self::ENTITAT, self::DIRECCIO, self::CODI_POSTAL, self::CIUTAT, self::TELEFON, self::EMAIL, self::PROFESSIO, self::DNI, self::DATA_NAIXEMENT, self::DONACIO, self::PERIODICITAT, self::FORMA_PAGAMENT, self::CC, self::OFICINA, self::DC, self::ENTITAT_COMPTE, self::TITULAR_COMPTE, self::NEWSLETTER, self::NB_PEDIDO, self::RESPONSE, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'nom', 'cognoms', 'entitat', 'direccio', 'codi_postal', 'ciutat', 'telefon', 'email', 'professio', 'dni', 'data_naixement', 'donacio', 'periodicitat', 'forma_pagament', 'cc', 'oficina', 'dc', 'entitat_compte', 'titular_compte', 'newsletter', 'nb_pedido', 'response', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Nom' => 1, 'Cognoms' => 2, 'Entitat' => 3, 'Direccio' => 4, 'CodiPostal' => 5, 'Ciutat' => 6, 'Telefon' => 7, 'Email' => 8, 'Professio' => 9, 'Dni' => 10, 'DataNaixement' => 11, 'Donacio' => 12, 'Periodicitat' => 13, 'FormaPagament' => 14, 'Cc' => 15, 'Oficina' => 16, 'Dc' => 17, 'EntitatCompte' => 18, 'TitularCompte' => 19, 'Newsletter' => 20, 'NbPedido' => 21, 'Response' => 22, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'nom' => 1, 'cognoms' => 2, 'entitat' => 3, 'direccio' => 4, 'codiPostal' => 5, 'ciutat' => 6, 'telefon' => 7, 'email' => 8, 'professio' => 9, 'dni' => 10, 'dataNaixement' => 11, 'donacio' => 12, 'periodicitat' => 13, 'formaPagament' => 14, 'cc' => 15, 'oficina' => 16, 'dc' => 17, 'entitatCompte' => 18, 'titularCompte' => 19, 'newsletter' => 20, 'nbPedido' => 21, 'response' => 22, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NOM => 1, self::COGNOMS => 2, self::ENTITAT => 3, self::DIRECCIO => 4, self::CODI_POSTAL => 5, self::CIUTAT => 6, self::TELEFON => 7, self::EMAIL => 8, self::PROFESSIO => 9, self::DNI => 10, self::DATA_NAIXEMENT => 11, self::DONACIO => 12, self::PERIODICITAT => 13, self::FORMA_PAGAMENT => 14, self::CC => 15, self::OFICINA => 16, self::DC => 17, self::ENTITAT_COMPTE => 18, self::TITULAR_COMPTE => 19, self::NEWSLETTER => 20, self::NB_PEDIDO => 21, self::RESPONSE => 22, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'nom' => 1, 'cognoms' => 2, 'entitat' => 3, 'direccio' => 4, 'codi_postal' => 5, 'ciutat' => 6, 'telefon' => 7, 'email' => 8, 'professio' => 9, 'dni' => 10, 'data_naixement' => 11, 'donacio' => 12, 'periodicitat' => 13, 'forma_pagament' => 14, 'cc' => 15, 'oficina' => 16, 'dc' => 17, 'entitat_compte' => 18, 'titular_compte' => 19, 'newsletter' => 20, 'nb_pedido' => 21, 'response' => 22, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new DonacioMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. DonacioPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(DonacioPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(DonacioPeer::ID);

		$criteria->addSelectColumn(DonacioPeer::NOM);

		$criteria->addSelectColumn(DonacioPeer::COGNOMS);

		$criteria->addSelectColumn(DonacioPeer::ENTITAT);

		$criteria->addSelectColumn(DonacioPeer::DIRECCIO);

		$criteria->addSelectColumn(DonacioPeer::CODI_POSTAL);

		$criteria->addSelectColumn(DonacioPeer::CIUTAT);

		$criteria->addSelectColumn(DonacioPeer::TELEFON);

		$criteria->addSelectColumn(DonacioPeer::EMAIL);

		$criteria->addSelectColumn(DonacioPeer::PROFESSIO);

		$criteria->addSelectColumn(DonacioPeer::DNI);

		$criteria->addSelectColumn(DonacioPeer::DATA_NAIXEMENT);

		$criteria->addSelectColumn(DonacioPeer::DONACIO);

		$criteria->addSelectColumn(DonacioPeer::PERIODICITAT);

		$criteria->addSelectColumn(DonacioPeer::FORMA_PAGAMENT);

		$criteria->addSelectColumn(DonacioPeer::CC);

		$criteria->addSelectColumn(DonacioPeer::OFICINA);

		$criteria->addSelectColumn(DonacioPeer::DC);

		$criteria->addSelectColumn(DonacioPeer::ENTITAT_COMPTE);

		$criteria->addSelectColumn(DonacioPeer::TITULAR_COMPTE);

		$criteria->addSelectColumn(DonacioPeer::NEWSLETTER);

		$criteria->addSelectColumn(DonacioPeer::NB_PEDIDO);

		$criteria->addSelectColumn(DonacioPeer::RESPONSE);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(DonacioPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			DonacioPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseDonacioPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseDonacioPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Donacio
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = DonacioPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return DonacioPeer::populateObjects(DonacioPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseDonacioPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseDonacioPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			DonacioPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Donacio $value A Donacio object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Donacio $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Donacio object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Donacio) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Donacio object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Donacio Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = DonacioPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = DonacioPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = DonacioPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				DonacioPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return DonacioPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Donacio or Criteria object.
	 *
	 * @param      mixed $values Criteria or Donacio object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseDonacioPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseDonacioPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Donacio object
		}

		if ($criteria->containsKey(DonacioPeer::ID) && $criteria->keyContainsValue(DonacioPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.DonacioPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseDonacioPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseDonacioPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Donacio or Criteria object.
	 *
	 * @param      mixed $values Criteria or Donacio object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseDonacioPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseDonacioPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(DonacioPeer::ID);
			$selectCriteria->add(DonacioPeer::ID, $criteria->remove(DonacioPeer::ID), $comparison);

		} else { // $values is Donacio object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseDonacioPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseDonacioPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the donacio table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(DonacioPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Donacio or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Donacio object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			DonacioPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Donacio) {
			// invalidate the cache for this single object
			DonacioPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(DonacioPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				DonacioPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Donacio object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Donacio $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Donacio $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(DonacioPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(DonacioPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(DonacioPeer::DATABASE_NAME, DonacioPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = DonacioPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Donacio
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = DonacioPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(DonacioPeer::DATABASE_NAME);
		$criteria->add(DonacioPeer::ID, $pk);

		$v = DonacioPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(DonacioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(DonacioPeer::DATABASE_NAME);
			$criteria->add(DonacioPeer::ID, $pks, Criteria::IN);
			$objs = DonacioPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseDonacioPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the DonacioPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the DonacioPeer class:
//
// Propel::getDatabaseMap(DonacioPeer::DATABASE_NAME)->addTableBuilder(DonacioPeer::TABLE_NAME, DonacioPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseDonacioPeer::DATABASE_NAME)->addTableBuilder(BaseDonacioPeer::TABLE_NAME, BaseDonacioPeer::getMapBuilder());

