<?php

/**
 * Base static class for performing query and update operations on the 'contacte' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Jul  7 09:52:35 2011
 *
 * @package    plugins.iogContactePlugin.lib.model.om
 */
abstract class BaseContactePeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'contacte';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.iogContactePlugin.lib.model.Contacte';

	/** The total number of columns. */
	const NUM_COLUMNS = 18;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'contacte.ID';

	/** the column name for the TIPUS_PERSONA field */
	const TIPUS_PERSONA = 'contacte.TIPUS_PERSONA';

	/** the column name for the NOM field */
	const NOM = 'contacte.NOM';

	/** the column name for the COGNOMS field */
	const COGNOMS = 'contacte.COGNOMS';

	/** the column name for the DNI field */
	const DNI = 'contacte.DNI';

	/** the column name for the DIRECCIO field */
	const DIRECCIO = 'contacte.DIRECCIO';

	/** the column name for the CODI_POSTAL field */
	const CODI_POSTAL = 'contacte.CODI_POSTAL';

	/** the column name for the CIUTAT field */
	const CIUTAT = 'contacte.CIUTAT';

	/** the column name for the PROVINCIA field */
	const PROVINCIA = 'contacte.PROVINCIA';

	/** the column name for the PAIS_RESIDENCIA field */
	const PAIS_RESIDENCIA = 'contacte.PAIS_RESIDENCIA';

	/** the column name for the TELEFON field */
	const TELEFON = 'contacte.TELEFON';

	/** the column name for the EMAIL field */
	const EMAIL = 'contacte.EMAIL';

	/** the column name for the DATA_NAIXEMENT field */
	const DATA_NAIXEMENT = 'contacte.DATA_NAIXEMENT';

	/** the column name for the NACIONALITAT field */
	const NACIONALITAT = 'contacte.NACIONALITAT';

	/** the column name for the IDIOMA_CONTACTE field */
	const IDIOMA_CONTACTE = 'contacte.IDIOMA_CONTACTE';

	/** the column name for the SEXE field */
	const SEXE = 'contacte.SEXE';

	/** the column name for the ACCEPTA_MAILING field */
	const ACCEPTA_MAILING = 'contacte.ACCEPTA_MAILING';

	/** the column name for the TEXT field */
	const TEXT = 'contacte.TEXT';

	/**
	 * An identiy map to hold any loaded instances of Contacte objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Contacte[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'TipusPersona', 'Nom', 'Cognoms', 'Dni', 'Direccio', 'CodiPostal', 'Ciutat', 'Provincia', 'PaisResidencia', 'Telefon', 'Email', 'DataNaixement', 'Nacionalitat', 'IdiomaContacte', 'Sexe', 'AcceptaMailing', 'Text', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'tipusPersona', 'nom', 'cognoms', 'dni', 'direccio', 'codiPostal', 'ciutat', 'provincia', 'paisResidencia', 'telefon', 'email', 'dataNaixement', 'nacionalitat', 'idiomaContacte', 'sexe', 'acceptaMailing', 'text', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::TIPUS_PERSONA, self::NOM, self::COGNOMS, self::DNI, self::DIRECCIO, self::CODI_POSTAL, self::CIUTAT, self::PROVINCIA, self::PAIS_RESIDENCIA, self::TELEFON, self::EMAIL, self::DATA_NAIXEMENT, self::NACIONALITAT, self::IDIOMA_CONTACTE, self::SEXE, self::ACCEPTA_MAILING, self::TEXT, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'tipus_persona', 'nom', 'cognoms', 'dni', 'direccio', 'codi_postal', 'ciutat', 'provincia', 'pais_residencia', 'telefon', 'email', 'data_naixement', 'nacionalitat', 'idioma_contacte', 'sexe', 'accepta_mailing', 'text', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'TipusPersona' => 1, 'Nom' => 2, 'Cognoms' => 3, 'Dni' => 4, 'Direccio' => 5, 'CodiPostal' => 6, 'Ciutat' => 7, 'Provincia' => 8, 'PaisResidencia' => 9, 'Telefon' => 10, 'Email' => 11, 'DataNaixement' => 12, 'Nacionalitat' => 13, 'IdiomaContacte' => 14, 'Sexe' => 15, 'AcceptaMailing' => 16, 'Text' => 17, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'tipusPersona' => 1, 'nom' => 2, 'cognoms' => 3, 'dni' => 4, 'direccio' => 5, 'codiPostal' => 6, 'ciutat' => 7, 'provincia' => 8, 'paisResidencia' => 9, 'telefon' => 10, 'email' => 11, 'dataNaixement' => 12, 'nacionalitat' => 13, 'idiomaContacte' => 14, 'sexe' => 15, 'acceptaMailing' => 16, 'text' => 17, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::TIPUS_PERSONA => 1, self::NOM => 2, self::COGNOMS => 3, self::DNI => 4, self::DIRECCIO => 5, self::CODI_POSTAL => 6, self::CIUTAT => 7, self::PROVINCIA => 8, self::PAIS_RESIDENCIA => 9, self::TELEFON => 10, self::EMAIL => 11, self::DATA_NAIXEMENT => 12, self::NACIONALITAT => 13, self::IDIOMA_CONTACTE => 14, self::SEXE => 15, self::ACCEPTA_MAILING => 16, self::TEXT => 17, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'tipus_persona' => 1, 'nom' => 2, 'cognoms' => 3, 'dni' => 4, 'direccio' => 5, 'codi_postal' => 6, 'ciutat' => 7, 'provincia' => 8, 'pais_residencia' => 9, 'telefon' => 10, 'email' => 11, 'data_naixement' => 12, 'nacionalitat' => 13, 'idioma_contacte' => 14, 'sexe' => 15, 'accepta_mailing' => 16, 'text' => 17, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new ContacteMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. ContactePeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(ContactePeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(ContactePeer::ID);

		$criteria->addSelectColumn(ContactePeer::TIPUS_PERSONA);

		$criteria->addSelectColumn(ContactePeer::NOM);

		$criteria->addSelectColumn(ContactePeer::COGNOMS);

		$criteria->addSelectColumn(ContactePeer::DNI);

		$criteria->addSelectColumn(ContactePeer::DIRECCIO);

		$criteria->addSelectColumn(ContactePeer::CODI_POSTAL);

		$criteria->addSelectColumn(ContactePeer::CIUTAT);

		$criteria->addSelectColumn(ContactePeer::PROVINCIA);

		$criteria->addSelectColumn(ContactePeer::PAIS_RESIDENCIA);

		$criteria->addSelectColumn(ContactePeer::TELEFON);

		$criteria->addSelectColumn(ContactePeer::EMAIL);

		$criteria->addSelectColumn(ContactePeer::DATA_NAIXEMENT);

		$criteria->addSelectColumn(ContactePeer::NACIONALITAT);

		$criteria->addSelectColumn(ContactePeer::IDIOMA_CONTACTE);

		$criteria->addSelectColumn(ContactePeer::SEXE);

		$criteria->addSelectColumn(ContactePeer::ACCEPTA_MAILING);

		$criteria->addSelectColumn(ContactePeer::TEXT);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(ContactePeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			ContactePeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseContactePeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseContactePeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Contacte
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = ContactePeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return ContactePeer::populateObjects(ContactePeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseContactePeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseContactePeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			ContactePeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Contacte $value A Contacte object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Contacte $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Contacte object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Contacte) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Contacte object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Contacte Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = ContactePeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = ContactePeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = ContactePeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				ContactePeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return ContactePeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Contacte or Criteria object.
	 *
	 * @param      mixed $values Criteria or Contacte object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseContactePeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseContactePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Contacte object
		}

		if ($criteria->containsKey(ContactePeer::ID) && $criteria->keyContainsValue(ContactePeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.ContactePeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseContactePeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseContactePeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Contacte or Criteria object.
	 *
	 * @param      mixed $values Criteria or Contacte object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseContactePeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseContactePeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(ContactePeer::ID);
			$selectCriteria->add(ContactePeer::ID, $criteria->remove(ContactePeer::ID), $comparison);

		} else { // $values is Contacte object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseContactePeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseContactePeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the contacte table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(ContactePeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Contacte or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Contacte object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			ContactePeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Contacte) {
			// invalidate the cache for this single object
			ContactePeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(ContactePeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				ContactePeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Contacte object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Contacte $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Contacte $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(ContactePeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(ContactePeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(ContactePeer::DATABASE_NAME, ContactePeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = ContactePeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Contacte
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = ContactePeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(ContactePeer::DATABASE_NAME);
		$criteria->add(ContactePeer::ID, $pk);

		$v = ContactePeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ContactePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(ContactePeer::DATABASE_NAME);
			$criteria->add(ContactePeer::ID, $pks, Criteria::IN);
			$objs = ContactePeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseContactePeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the ContactePeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the ContactePeer class:
//
// Propel::getDatabaseMap(ContactePeer::DATABASE_NAME)->addTableBuilder(ContactePeer::TABLE_NAME, ContactePeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseContactePeer::DATABASE_NAME)->addTableBuilder(BaseContactePeer::TABLE_NAME, BaseContactePeer::getMapBuilder());

